---

config_project:
  path: "./TwoModeShroom_smooth_meander_2024.aedt"
  design_name: "DoubleCavityWithChip"
  version: "2024.2"

junctions:
  - name: "line_jj1"
    label: "transmon"
    inductance_variable_name: "Lj"

modes_and_labels:
  - labels:
      - "transmon"
      - "readout"
      - "purcell"

    modes:
      - inference_type: "manual"
        args:
          mode_number: 1
          label: "transmon"

      - inference_type: "order"
        args:
          num: 2
          min_or_max: "min"
          ordered_labels:
            - "readout"
            - "purcell"
          quantity: "q_factor"

  - labels:
      - "transmon"
      - "cavity_low"
      - "cavity_high"

    modes:
      - inference_type: "manual"
        args:
          mode_number: 1
          label: "transmon"

      - inference_type: "manual"
        args:
          mode_number: 2
          label: "cavity_low"

      - inference_type: "manual"
        args:
          mode_number: 3
          label: "cavity_high"




sweep:
  name: 'product'
  args:
    variables:
      - name: "purcell_length"
        values: [ 5.76 ]
        unit: "mm"



...