site_name: My Project Docs
site_description: Simulation framework documentation
site_url: https://example.com/
strict: true

theme:
  name: 'material'
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - content.code.copy
    - content.tabs.link
    - toc.follow
  palette:
    - scheme: default
      primary: blue
      accent: blue
    - scheme: slate
      primary: blue
      accent: blue
#  palette:
#    - scheme: slate
#      primary: red
#      accent: red
#  font:
#    text: 'Spectral'
#    code: 'Fira Code'



nav:
  - Home: index.md
  - Guides:
      - Quickstart: guides/quickstart.md
  - API Reference:
        - EigenmodeAnalysis: api/eigenmode_analysis.md
        - EigenmodeResults: api/eigenmode_results.md
        - QuantumEpr: api/quantum_epr.md
        - QuantumResult: api/quantum_results.md
        - WorkflowConfig: api/workflow_config.md
        - PrepareFolderConfig: api/prepare_folder_config.md
        - PyaedtFileParameters: api/pyaedt_file_parameters.md
        - DesignVariableBuilder: api/design_variable_builder.md
        - FunctionBuilder: api/function_builder.md
        - ModuleBuilder: api/module_builder.md

plugins:
  - offline
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_signature_annotations: true
            separate_signature: true
            merge_init_into_class: true
            filters: ["!^_"]
            heading_level: 2  #
          rendering:
            show_root_toc_entry: true

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.extra
  - pymdownx.tabbed:
      alternate_style: true

