[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pysubmit"
version = "1.0.0"
dependencies = [
    "qutip",
    "pyaedt[all]",
    "pint",
    "h5py>=3.12.1",
]
requires-python = ">=3.11"
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python"
]


[project.scripts]
submit-run = "pysubmit:submit_run"
submit-prepare = "pysubmit:submit_prepare"
submit-check = "pysubmit:submit_check"

