[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pysubmit"
version = "2.0.0"
dependencies = [
    "qutip",
    "pyaedt[all]",
    "pint",
    "h5py>=3.12.1",
    "pandas>=2.2.3",
    "pydantic_yaml", # Added typer as a dependency
    "typer[all]",
    "pytest>=8.3.4",
    "drawing @ git+https://github.com/RosenblumLab/drawing.git",
]
requires-python = ">=3.11"
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python"
]


[project.scripts]
workflow = "pysubmit.cli.main:app"


