builder:
    additional_files: null
    args: {}
    path: builder_scripts\script_builder_function.py
    type: script_builder
builder_sweep:
- constants: {}
  parameters:
      value:
      - 10mm
      - 12mm
      - 14mm
      - 16mm
  type: zip
  use_compound_types: true
data_handler:
    aggregations_directory: results_6\aggregations
    aggregations_dirname: aggregations
    counter: 3
    grouping_config:
        my_aggregation:
        - build_parameters
        - classical
    iterations_directory: results_6\iterations
    iterations_dirname: iterations
    last_iteration_path: results_6\iterations\iteration_3
    overwrite: false
    results_directory: results_6
    results_dirname: results_6
    root_directory: .
    use_unique: true
session_parameters:
    close_on_exit: true
    design_name: temp
    file_path: designs\simple_design.aedt
    new_desktop: true
    non_graphical: false
    version: '2024.2'
simulations:
    classical:
        cores: 4
        design_name: my_design
        gpus: 0
        setup_name: Setup1
        setup_parameters: {}
        type: eigenmode
