---

config_project:
  path: "./TwoModeShroom_smooth_meander_2024.aedt"
  design_name: "OnlyChip"
  version: "2024.2"

junctions:
  - name: "line_jj1"
    label: "transmon"
    inductance_variable_name: "Lj"

modes_and_labels:
  -
    labels:
      - "transmon"
      - "readout"
      - "purcell"

    modes:
      - inference_type: "manual"
        args:
          mode_number: 1
          label: "transmon"

      - inference_type: "order"
        args:
          num: 2
          min_or_max: "min"
          ordered_labels:
            - "readout"
            - "purcell"
          quantity: "q_factor"


hfss_variables:
#  - name: "spacer"
#    value: 1.0
#    unit: "mm"
#  - name: "Lj"
#    value: 1.0
#    unit: "nH"
#  - name: "spacer"
#    value: 1.0
#    unit: "mm"


...