---

config_project:
  path: "./TwoModeShroom_smooth_meander_2024.aedt"
  design_name: "DoubleCavity"
  version: "2024.2"
  non_graphical: False

#junctions:
#  - name: "line_jj1"
#    label: "transmon"
#    inductance_variable_name: "Lj"

#modes_and_labels:
#  - labels:
#      - "transmon"
#      - "readout"
#      - "purcell"
#
#    modes:
#      - inference_type: "manual"
#        args:
#          mode_number: 1
#          label: "transmon"
#
#      - inference_type: "order"
#        args:
#          num: 2
#          min_or_max: "min"
#          ordered_labels:
#            - "readout"
#            - "purcell"
#          quantity: "q_factor"


#sweep:
#  name: 'product'
#  args:
#    variables:
#      - name: "spacer"
#        values: [ 0.01, 0.2 ]
#        unit: "mm"


builder:
  builder:
    type: 'two_mode_srf_cavity'
    build_design_name: 'OnlyCavity_tmp'
    dst_design_name: 'DoubleCavity'
    sweep:
      name: 'product'
      args:
        variables:
          - name: "full_cell_Rc"
            values: [30, 40]
            unit: "mm"
          - name: "half_cell_Rc"
            values: [30, 40]
            unit: "mm"

