default_meander_radius: &meander_radius
  - 100
default_meander_spacing: &meander_spacing
  - 220
default_meander_num_turns: &num_turns
#  - 9
  - 10
  - 12
default_meander_wire_width: &wire_width
  - 80
default_meander_height: &meander_height
  - 1600


builder:
  args:
    design_name: my_design
    setup_name: Setup1
    junction_inductance:
      value: 10
      unit: nh
    max_elements:
  type: script_builder
  path: ./chip.py

builder_sweep:
  - data:
      chip_base_length:
        value: 23.25
        unit: mm
      spacer_length:
        value: 0.001
        unit: mm

      chip_base_mesh:
        - 200um
      readout_mesh:
        - 50um
      readout_mesh_box:
        - 200um
      purcell_mesh:
        - 50um
      purcell_mesh_box:
        - 200um
      transmon_mesh:
#        - 10um
#        - 20um
#        - 50um
        - 50um
#        - 50um
      transmon_mesh_box:
#        - 50um
#        - 100um
        - 200um
#        - 200um
#        - 200um
      junction_mesh:
#        - 0.5um
#        - 0.5um
#        - 0.5um
#        - 0.2um
        - 0.05um
#        - 0.1um
#        - 0.05um
#        - 0.01um
#        - 0.1um
      junction_mesh_box:
#        - 2um
#        - 2um
#        - 2um
#        - 0.75um
        - 0.5um
#        - 0.25um
#        - 0.25um
#        - 0.1um
#        - 1um
      vacuum_mesh:
        - 2mm
    type: zip
  - data:
      purcell_wire_width: *wire_width
      purcell_radius: *meander_radius
      purcell_spacing: *meander_spacing
      purcell_num_turns: *num_turns

      readout_padding_length:
        - 750

#      purcell_padding_length:
#        - 650

      purcell_padding_length:
#        - 600
#        - 625
        - 650
#        start: 620
#        end: 750
#        step: 20
#        as_type: int

      readout_wire_width: *wire_width
      readout_radius: *meander_radius
      readout_spacing: *meander_spacing
      readout_num_turns: *num_turns
      purcell_height: *meander_height
      readout_height: *meander_height

    type: product


data_parameters:
  project_name: testing_workflow
  root_directory: check_resonator_frequency_with_cavity

session_parameters:
  close_on_exit: true
  file_path: ./check_resonator_frequency_with_cavity.aedt
  new_desktop: true
  non_graphical: false
  version: '2024.2'

simulations:
  - cores: 4
    design_name: my_design
    setup_name: Setup1
    formatter_args: null
    formatter_type: freq_and_q_factor
    gpus: 0
    setup_parameters:
      MaximumPasses: 4
      MinimumConvergedPasses: 1
      MinimumPasses: 1
      MinimumFrequency: 2GHz
      NumModes: 20
      MaxDeltaFreq: 0.2
      ConvergeOnRealFreq: True
      PercentRefinement: 30
      BasisOrder: -1
      DoLambdaRefine: True
      DoMaterialLambda: True
      SetLambdaTarget: False
      Target: 0.4
      UseMaxTetIncrease: False
    type: eigenmode

#  - design_name: my_design
#    formatter_args: null
#    formatter_type: null
#    junctions_infos:
#    - inductance_variable_name: junction_inductance
#      name: junction_line
#    modes_to_labels:
#        labels:
#        - transmon
#        - purcell
#        - readout
#        modes:
#        - args:
#              label: transmon
#              mode_number: 1
#          inference_type: manual
#        - args:
#              label: purcell
#              mode_number: 2
#          inference_type: manual
#        - args:
#              label: readout
#              mode_number: 3
#          inference_type: manual
#    type: quantum_epr
