---

config_project:
  path: "./CavityAndChip.aedt"
  design_name: "cavity_and_chip"
  version: "2024.2"
  setup_name: "Setup1"
  max_passes: 3
  min_passes: 2
  non_graphical: False
  cores: 12
  gpus: 0

junctions:
  - name: "line_jj1"
    inductance_variable_name: "Lj"

modes_and_labels:
  - labels:
      - "transmon"
      - "cavity_low_mode"
      - "cavity_high_mode"

    modes:
      - inference_type: "manual"
        args:
          mode_number: 1
          label: "transmon"

      - inference_type: "manual"
        args:
          mode_number: 2
          label: "cavity_low_mode"

      - inference_type: "manual"
        args:
          mode_number: 3
          label: "cavity_high_mode"

#      - inference_type: "manual"
#        args:
#          num: 2
#          min_or_max: "min"
#          ordered_labels:
#            - "cavity_low_"
#            - "purcell"
#          quantity: "freq"


sweep:
  name: 'product'
  args:
    variables:
      - name: "Lj"
        values: [11, 12]
        unit: "nH"


builder:
  builder:
    type: 'two_mode_srf_cavity'
    sweep:
      name: 'product'
      args:
        variables:
          - name: "full_cell_Rc"
#            values: [ 28.  , 28.25, 28.5 , 28.75, 29.  , 29.25, 29.5 , 29.75, 30.  ,
#                      30.25, 30.5 , 30.75, 31.  , 31.25, 31.5 , 31.75, 32. ]
            values: [31]
            unit: "mm"
          - name: "half_cell_Rc"
            values: [31]
#            values: [ 28.  , 28.25, 28.5 , 28.75, 29.  , 29.25, 29.5 , 29.75, 30.  ,
#                      30.25, 30.5 , 30.75, 31.  , 31.25, 31.5 , 31.75, 32. ]
            unit: "mm"

